#!/usr/bin/env python3
"""Usage: python3 gen_wizardtorch_art.py <panefx/src> <amtui/fx>

Mechanically convert panefx's still-art and frame-reel Rust sources to Go.

Also prints FNV-1a checksums computed straight from the Rust text, which the
Go tests hard-code and recompute from the Go data."""
import re, sys, os

SRC = sys.argv[1]
OUT = sys.argv[2]

def fnv(data: bytes) -> int:
    h = 0x811C9DC5
    for b in data:
        h ^= b
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h

def doc_comment(text):
    lines = []
    for l in text.splitlines():
        if l.startswith('//!'):
            lines.append('//' + l[3:])
        else:
            break
    return lines

checks = {}

for name in ['wizardtorch', 'tgevil', 'wzfire', 'raalien']:
    text = open(os.path.join(SRC, f'{name}_art.rs')).read()
    cols = int(re.search(r'pub const COLS: usize = (\d+);', text).group(1))
    rows = int(re.search(r'pub const ROWS: usize = (\d+);', text).group(1))
    body = text[text.index('pub const ART'):]
    body = body[body.index('= [') + 3: body.index('\n];')]
    art = re.findall(r'^\s*"([^"\\]*)",\s*$', body, re.M)
    assert len(art) == rows, (name, len(art), rows)
    for r in art:
        assert len(r) == cols, (name, r)
    doc = doc_comment(text)
    out = ['// Code generated by gen_wizardtorch_art.py from panefx src/%s_art.rs. DO NOT EDIT.' % name, '']
    out += doc
    out += ['', 'package fx', '',
            'const (',
            f'\t{name}Cols = {cols}',
            f'\t{name}Rows = {rows}',
            ')', '',
            f'// {name}Art is one row per line, one char per cell:',
            '//',
            '//\tspace = empty, `.:*#` = quarter/half/three-quarter/full shade,',
            '//\t`TBLR` = top/bottom/left/right half blocks.',
            '//',
            '// ASCII stand-ins for the CP437 blocks so the source stays 7-bit.',
            f'var {name}Art = [{name}Rows]string{{']
    out += ['\t"%s",' % r for r in art]
    out += ['}', '']
    open(os.path.join(OUT, f'{name}_art.go'), 'w').write('\n'.join(out))
    checks[name] = (cols, rows, fnv('\n'.join(art).encode()))

# --- fish loop ---
text = open(os.path.join(SRC, 'fishloop_art.rs')).read()
cols = int(re.search(r'pub const COLS: usize = (\d+);', text).group(1))
rows = int(re.search(r'pub const ROWS: usize = (\d+);', text).group(1))
fps = int(re.search(r'pub const FPS: u64 = (\d+);', text).group(1))
bg = re.search(r'pub const BG: \(u8, u8, u8\) = \((\d+), (\d+), (\d+)\);', text).groups()
pal_body = text[text.index('pub const PALETTE'):]
pal_body = pal_body[pal_body.index('= [') + 3: pal_body.index('\n];')]
palette = [tuple(map(int, m)) for m in re.findall(r'\((\d+), (\d+), (\d+)\)', pal_body)]
n = int(re.search(r'pub const PALETTE: \[\(u8, u8, u8\); (\d+)\]', text).group(1))
assert len(palette) == n
fr_body = text[text.index('pub const FRAMES'):]
nframes = int(re.search(r'pub const FRAMES: \[&\[Cell\]; (\d+)\]', text).group(1))
fr_body = fr_body[fr_body.index('= [') + 3: fr_body.index('\n];')]
order = re.findall(r'(\w+),', fr_body)
assert len(order) == nframes
statics = {}
for m in re.finditer(r'static (\w+): &\[Cell\] = &\[(.*?)\n\];', text, re.S):
    cells = re.findall(r"\((\d+), (\d+), '(.)', (\d+)\),", m.group(2))
    raw = re.findall(r'\(', m.group(2))
    assert len(cells) == len(raw), m.group(1)
    statics[m.group(1)] = [(int(c), int(r), g, int(i)) for c, r, g, i in cells]
frames = [statics[o] for o in order]
for f in frames:
    for c, r, g, i in f:
        assert c < 256 and r < 256 and i < n and ord(g) < 128 and g != ' '

doc = doc_comment(text)
out = ['// Code generated by gen_wizardtorch_art.py from panefx src/fishloop_art.rs. DO NOT EDIT.', '']
out += doc
out += ['//', '// In Go each frame is a packed string, four bytes per lit cell:',
        '// col, row, glyph, palette index -- 7-bit safe, and a byte per field',
        '// rather than a 16-byte struct, so the reel adds a few KB to the binary.',
        '', 'package fx', '',
        'const (',
        f'\tfishloopCols = {cols}',
        f'\tfishloopRows = {rows}',
        '\t// fishloopFPS is the frame rate the piece was authored at.',
        f'\tfishloopFPS = {fps}',
        ')', '',
        '// fishloopBG is the canvas background the artist chose.',
        'var fishloopBG = RGB{%s, %s, %s}' % bg, '',
        '// fishloopPalette is every colour the piece uses.',
        f'var fishloopPalette = [{n}]RGB{{']
out += ['\t{%d, %d, %d},' % p for p in palette]
out += ['}', '', '// fishloopFrames is one packed string per frame, in order.',
        f'var fishloopFrames = [{nframes}]string{{']
fnvdata = b''
for k, f in enumerate(frames):
    out.append(f'\t// {order[k]}: {len(f)} cells')
    chunks = []
    for s in range(0, len(f), 12):
        part = f[s:s + 12]
        chunks.append('"' + ''.join('\\x%02x\\x%02x%s\\x%02x' % (c, r, g if g not in '"\\' else '\\' + g, i) for c, r, g, i in part) + '"')
    if not chunks:
        chunks = ['""']
    out.append('\t' + ' +\n\t\t'.join(chunks) + ',')
    for c, r, g, i in f:
        fnvdata += bytes([c, r, ord(g), i])
out += ['}', '']
open(os.path.join(OUT, 'fishloop_art.go'), 'w').write('\n'.join(out))
checks['fishloop'] = (cols, rows, fps, nframes, [len(f) for f in frames], fnv(fnvdata), frames[0][0], frames[-1][-1])
for k, v in checks.items():
    print(k, v)
